# Generated by Django 2.1.5 on 2019-02-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(default='Summary is in GitHub ReadMe.', max_length=200)),
                ('githubURL', models.CharField(default='https://github.com/Deep9z', max_length=200)),
                ('fullJobDetail', models.CharField(default='Summary is in GitHub ReadMe.', max_length=200)),
            ],
        ),
    ]
