# Generated by Django 2.1.5 on 2019-02-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='fullJobDetail',
            field=models.CharField(default='Summary is in GitHub ReadMe.', max_length=2000),
        ),
    ]
