# Generated by Django 2.1.5 on 2019-02-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190208_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobName',
            field=models.CharField(default='Project Details', max_length=200),
        ),
    ]
